export const SPOTIFY_SET_TOKEN = "SPOTIFY_SET_TOKEN";
export const SPOTIFY_GET_USER_PLAYLISTS = "SPOTIFY_GET_USER_PLAYLISTS";
export const SPOTIFY_GET_DISCOVER_WEEKLY_PLAYLIST = "SPOTIFY_GET_DISCOVER_WEEKLY_PLAYLIST";
export const SPOTIFY_GET_USER_DETAILS = "SPOTIFY_GET_USER_DETAILS";
export const SET_PLAYING = "SET_PLAYING";
export const SET_ITEM = "SET_ITEM";
