export const SPOTIFY_SET_TOKEN = "SPOTIFY_SET_TOKEN";
export const SPOTIFY_GET_USER_PLAYLISTS = "SPOTIFY_GET_USER_PLAYLISTS";
export const SPOTIFY_GET_DISCOVER_WEEKLY_PLAYLIST = "SPOTIFY_GET_DISCOVER_WEEKLY_PLAYLIST";
